### PR TITLE
A proposal for optionally enabling commit and config locks

### PR DESCRIPTION
**Pull request by hkam40k**

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
@ktbyers @mirceaulinic I know you are not maintaining this repo, but wanted to get your opinion. I would like to stay as close to NAPALM proper as possible, but not really sure how to handle use cases like these.

**Comment by hkam40k** [comment]
For what its wort, the NAPALM JunOS plugin also implements locking mechanics.

**Comment by mirceaulinic** [comment]
> Use of locking is also just optional, not enforced.

Just to clarify, with Junos, locking is not optional while loading configuration - what is optional is whether the config is locked as soon as the connection is established, or only when loading the configuration.

>  but not really sure how to handle use cases like these.

What is it the use case specifically, @itdependsnetworks?

**Comment by hkam40k** [comment]
> > Use of locking is also just optional, not enforced.
> 
> Just to clarify, with Junos, locking is not optional while loading configuration - what is optional is whether the config is locked as soon as the connection is established, or only when loading the configuration.

Sorry, in my response I meant that in my proposal using locking is optional. It is also possible to keep using it as before (which is the default), with no locking taking place.

**Comment by itdependsnetworks** [comment]
@mirceaulinic yes, I was not aware where else there was usage of a lock.

**Comment by hkam40k** [comment]
Hello, how do you find this proposal? Do you think think the commit and config locking belongs in the repository?

**Comment by mirceaulinic** [comment]
I'm personally not familiar with PAN-OS, does it have a config locking mechanism natively?

Either way, I think I agree with adding commit and config locking whether the platform supports it or this needs to be coded into this driver.

**Comment by hkam40k** [comment]
> I'm personally not familiar with PAN-OS, does it have a config locking mechanism natively?
> 
> Either way, I think I agree with adding commit and config locking whether the platform supports it or this needs to be coded into this driver.

PAN-OS does have locking mechanics natively: A different lock for committing and editing the config. The implementation I'm proposing takes both locks, by calling PAN-OS CLI commands over SSH.

**Comment by hkam40k** [comment]
Hello,

Ping for processing of this PR.

I've made some improvements to the locking mechanics: automatic retry/wait in case of ongoing commit on the device or reserved locks. However, before I go about updating the PR and fixing the conflicts, I'd like to know if you believe this proposal should eventually be incorporated or not. The PR is basically just exposing more features of the PA platform to be optionally usable by the driver. Also if you have any comments or change requests for improving it further, those would be very welcome!

**Pull request closed without merging**
